[project]
name = "logger-samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.4",
    "opentelemetry-sdk>=1.32.1",
]
