[project]
name = "logger-samples"
version = "1.0.0"
description = "Sample Loggers to illustrate the use of OpenTelemetry for logging and tracing"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.4",
    "opentelemetry-sdk>=1.32.1",
]
